# Generated by Django 5.1.1 on 2025-12-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_review_options_alter_review_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pub_date'], 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
