# Generated by Django 5.1.1 on 2025-12-14 14:05

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[categories.models.validate_year], verbose_name='Год издания'),
        ),
    ]
